POST http://127.0.0.1:8080/login?username=oyc&password=oyc
Accept: */*
Cache-Control: no-cache



###

GET http://127.0.0.1:8080/admin
Accept: */*
Cache-Control: no-cache
token: eyJhbGciOiJIUzUxMiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWKi5NUrJSyq9MVtJRKi1OLQrKz0kFCgT5-7jGO7r4evrpgJmhwa5BQBWpFQVKVoZmRkYGluaWlka1AGNFmr1AAAAA.HCtY25g-zW2kH5kthBBHmIofX0RBp0GD6WBUT2ssGvyZpZ3hWUsN5dgnGew-MEM9LIx68G-sbXQNCdAqJNKgqg
