POST http://127.0.0.1:8080/login?username=oyc&password=oyc
Accept: */*
Cache-Control: no-cache



###

GET http://127.0.0.1:8080/admin
Accept: */*
Cache-Control: no-cache
token: eyJhbGciOiJIUzUxMiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWKi5NUrJSyq9MVtJRKi1OLQrKz0kFCgT5-7jGO7r4evrpgJmhwa5BQBWpFQVKVoZmRkZGZpZGpha1ABHOl0BAAAAA.ROWZHtLZmhhK1P2xbxWI0YZYzk9lm_lM8pyJAMH6y7HUR-Wpuo2wcuDtmKxYOhD14mPjy-nZ-9fCJgWc7GvljQ
