spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: 199418
          url: jdbc:mysql://192.168.80.128:3306/springboot-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          username: root
          password: 199418
          url: jdbc:mysql://192.168.80.128:3306/springboot-demo2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
      mp-enabled: true
logging:
  level:
    com.cdx: debug
